### ISSUE TITLE
Directory 구조 변경

### ISSUE THREAD

**Issue by Jehaechan** [lieion/OpenSource_Final_Project#11]
```bash
├── public
│   ├── img
│   │    └── (image files...)
│   ├── js
│   │    └── (js files...)
│   ├── css
│   │    └── (css files...)
│   └── (html files...)
└── (node files...) 
``` 
다음과 같이 디렉토리 구조를 변경하고자 하는데 괜찮을까요?
+ **public directory** client에게 serve될 파일
+ **root directory** node용 javascript파일

위와 같이 구성하였습니다.

**Comment by lieion** [comment]
#12 와도 연결되는 이야기이지만 개인적인 의견으로는 사용자 접근성을 위해서라도 index.html 파일은 root에 두는 것이 어떨까요?

**Comment by Jehaechan** [comment]
말씀해주신 내용대로 수정하여 다시 commit 완료하였습니다!
