### ISSUE TITLE
현재  진행 상황 update

### ISSUE THREAD

**Issue by Jehaechan** [lieion/OpenSource_Final_Project#14]
### 진행 완료
1. ~~각 카페별 지도 페이지 추가~~
1. ~~각 카페별 메뉴 페이지 추가~~

### 진행 예정
1. Menu Page에서 각 사용자가 주문한 메뉴 종류와 개수를 입력받고, 총 금액을 계산해주는 기능 추가

### 필요한 기능 요청 @lieion 
``` node
   let menu = {
      <menu_name>: <price>
   }
```
위와 같이 menu라는 객체에 각 카페의 메뉴와 가격
``` node
   let order_list = {
      <menu_name>: <count>
   }
```
order_list에 현재 사용자가 주문한 메뉴명과 개수  
(총 금액은 "total": <총 금액>과 같은 형태로 order_list 맨 아래에 추가하도록 하겠습니다. count가 0인 menu는 order_list에 추가하지 않도록 하겠습니다.)

이렇게 구성하여 order_list를 넘겨드릴테니, **주문 내역을 ~~local storage~~ server에 저장하는 기능**을 구현해주시면 감사하겠습니다! 
***
## Additional
추가적으로 필요한 기능이나 페이지가 있으면 Comment로 남겨주세요 😃

**Comment by lieion** [comment]
**카페 메뉴 관련**
1. 현재 카페 메뉴 관련해서 개발이 진행 중이었으며, 서버가 실행될 때 로컬에 저장된 json 파일을 읽어서 로그인 내역처럼 서버의 storage에 저장할 예정입니다. 

**추가 기능 관련**
홈 메인 화면 관련해서 링크 연결 부탁드립니다.

**버그 관련**
업데이트 이후 process->public 디렉토리 교체 이후 html 파일에서 아직 변경되지 않는 부분이 많아 버그가 나타나고 있습니다.

**Comment by Jehaechan** [comment]
**카페 메뉴 관련**
1. 현재 카페 메뉴 관련해서 개발이 진행 중이었으며, 서버가 실행될 때 로컬에 저장된 json 파일을 읽어서 로그인 내역처럼 서버의 storage에 저장할 예정입니다.   

*->카페 메뉴를 json파일로 저장해놓고 해당 json파일을 읽어 menu페이지를 구성한다는 말씀이신가요?*  @lieion 

**추가 기능 관련**
홈 메인 화면 관련해서 링크 연결 부탁드립니다.  

*->**index.html**에서 **login**페이지와 **sign-up**페이지로 가는 링크 수정하였습니다.*

**버그 관련**
업데이트 이후 process->public 디렉토리 교체 이후 html 파일에서 아직 변경되지 않는 부분이 많아 버그가 나타나고 있습니다.   

*->일단 *index.html*에서는 버그를 확인하여 수정하였는데, 추가적으로 발견되는 부분 있으면 Comment로 남겨주세요!*
