### ISSUE TITLE
현재 진행상황 Update

### ISSUE THREAD

**Issue by lieion** [lieion/OpenSource_Final_Project#17]
#
+ **Term Server 관련 개발 정보**
현재 개발 완료된 정보
~~1. 각 카페 별 json file~~
json 파일이 필요하기 때문에 디렉토리 구조를 public 내부에 json 파일 폴더를 추가하였습니다.(./public/json)
~~2. Blue Port 가격 계산~~
가격 계산 구조가 Post로 주문한 음료의 개수를 각각 보내고 서버에서 가격을 계산한 뒤에 응답으로 그 가격을 보내면 출력해주는 방식으로 구현하였습니다. 
~~3. Blue Port 주문~~
~~4. myPage에서 Blue Port 주문정보 출력~~
개발 예정 정보
_1. 카페 관리자_
카페 관리하는 입장에서의 페이지 제작, 신고 추가 (~29)
_2.다른 카페 부분 구현_
Blue Port 카페만 구현되었기 때문에 다른 카페 부분도 구현 필요 (~30)

+ **Suggestion**
다른 카페 부분도 구조가 비슷해서 변수만 수정하면 구현하는데 문제가 없을 것 같습니다. 
   
+ **Additional Info**
개발할 시 주의해야 할 사항, 다른 file과의 dependency 등 추가적으로 알려줘야 할 내용

jquery를 사용하기 때문에 충돌이 나는 경우

`<script src="https://code.jquery.com/jquery-1.12.4.js"></script>`
 `<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>`

head에 불러오지 않아서 일어나는 일이 잦았습니다.

이번 업데이트 이후 file storage 관련 npm 'fs'를 추가로 더 사용합니다.
`npm install fs` 이 요구됩니다.

Object에 더 필요한 property가 더 있다면 추가하도록 하겠습니다.

#

**Comment by Jehaechan** [comment]
- 현재 #14 에서 말씀드린 대로 Menu page에서 각 사용자가 주문한 메뉴 종류와 개수를 입력받고, 총 금액을 계산해주는 기능을 구현 완료하였습니다.
- 총 금액 계산은 사용자가 +나 -button을 누를 때 마다 갱신되어야 하기 때문에 서버에서 계산하는 것이 아닌 사용자 local에서 계산하고, server측에는 order버튼을 누르는 순간 총 주문 내역과 총 가격만 보내는 것으로 구상하고 완성하였는데, 서로 약간 착오가 있었던 것 같네요. 같은 기능을 구현한것 같습니다.
- 저는 현재 모든 카페에 대해서
  1. menu(menu_name + price)
  1. menu_name
  1. price
  1. 사용자가 주문한 개수
 
  이렇게 네가지 value를 server쪽에 전달할 수 있게 준비해놓은 상태입니다. (server측에서 어떤 정보를 필요로 할지 몰라 일단 전부 준비해두었습니다.)

@lieion 님이 구현하신 내용대로 가는게 나을지, 아니면 코드를 약간 수정할지 선택해야할 것 같습니다.

**Comment by lieion** [comment]
그럼 dev 말고 다른 branch에 push 해놓으시면 dev merge 진행한 뒤에 main에 merge 진행하도록 하겠습니다. 코드를 보고 수정방향을 고민해봐야할 것 같습니다.

**Comment by Jehaechan** [comment]
현재 **menu_order** 브랜치에 푸쉬해놓았습니다!

**Comment by lieion** [comment]
푸쉬한 정보 바탕으로 수정 완료하였습니다. 일단 Order 부분은 모두 완료하였습니다.

**Comment by Jehaechan** [comment]
확인하였습니다. 다만 현재 Network Graph를 보니 menu_order를 dev에 merge 하지 않은 상태인 것 같은데 dev branch에서
``` bash
git merge menu_order
```
한 다음 다시 commit하여 원격으로 push해주실 수 있을까요?

**Comment by Jehaechan** [comment]
- menu_order와 dev branch를 merge한 뒤 main에 merge까지 **완료**하였습니다. 
- 해당 issue는 close하도록 하겠습니다.
