### ISSUE TITLE
현재 진행 상황 Update

### ISSUE THREAD

**Issue by lieion** [lieion/OpenSource_Final_Project#19]
#
+ **Term Server 관련 개발 정보**
현재 개발 완료된 정보
~~1. 각 카페 별 주문 및 myPage 반영~~
~~2. 주문 부분 로그인 관련해서 로그인 로그아웃 버튼 통합~~

+ **개발 중인 정보**
1. 카페 관리자 
카페 관리하는 입장에서의 페이지 제작, 신고 추가 (29) - MyPage와 비슷하게 처리 예정 + 신고 버튼 추가
2. 개발자, 관리자 페이지
신고 당한 사람 확인 (30) - MyPage와 비슷하게 처리 예정 
3. 카페 관리자 관련 회원가입 수정 (예외 처리)
학번 9000000000-9999999999는 카페 관리자에게 (3등분해서 각 카페에게)
학번 0000000000-0999999999는 관리개발자에게 제공될 예정입니다.

+ **Suggestion**
**각 카페 별 지도 부분 로그인 부분 확인**해야할 것 같습니다
홈 부분 밋밋한 것 해결하는 것이랑 README.md 부분 작성이 조금은 필요할 것 같습니다.  
관련해서 **task division**이 필요할 듯 싶습니다.

+ **Additional Info**
개발 시 현재 임시로 사용하고 있는 아이디와 비밀번호는 각각 '0000000001', 'qwerty123!'입니다. 관리자 직책으로 되어있으며
개발에 도움을 위해서 더 필요할 시 dummy User를 추가할 예정입니다.

버그 더 있다면 수정하겠습니다.

#

**Comment by Jehaechan** [comment]
- 일단 개인적인 의견으로는 신고 기능은 필수가 아니기 때문에 일단 처음으로 배포되는 버전에는 포함시키지 않아도 될 것 같습니다. 어떻게 하는게 좋을지 의견 부탁드립니다!
- 지도 부분에서는 어떤 부분이 문제인가요?
- 앞으로 더 필요한 부분이
  1. 관리자 페이지 - order 확인
  2. 신고기능 추가(협의 필요)
  3. index.html 개선
  4. README 작성
  5. 관리자 회원가입  

   이렇게 5가지가 맞을까요?

**Comment by lieion** [comment]
- 신고기능이 없으면 관리자 부분이 붕 떠버려서 구현하려고 했고, 난이도도 크게 높지 않아 금방 구현될 것 같습니다.

- 지도 부분은 위의 로그인 회원가입 버튼 부분을 현재 로그인하면 로그아웃 My Page로 바꾸는 작업이 진행 중입니다.

- 네 지금 5는 해결완료했고 1,2,3,4 부분만 해결하면 될 것 같습니다.
