### ISSUE TITLE
현재 진행 상황

### ISSUE THREAD

**Issue by lieion** [lieion/OpenSource_Final_Project#20]
#
+ **Term Server 관련 개발 정보**
현재 개발 완료된 정보
~~1. 카페 관리자~~
카페 관리하는 입장에서의 페이지 제작, 신고 추가- MyPage와 비슷하게 처리 예정 + 신고 버튼 추가
~~2. 개발자, 관리자 페이지~~
신고 당한 사람 확인 - MyPage와 비슷하게 처리 예정 
~~3. 카페 관리자 관련 회원가입 수정 (예외 처리)~~
학번 9,000000000-9999999999는 카페 관리자에게 (100,000,000개 아이디 만큼 각 카페에게)
학번 0000000,000-0999999999는 관리개발자에게 제공될 예정입니다.
~~4. 사용자가 커피 완성 여부 확인 가능 (제조 중 > 완성 2단계)~~
~~5. 사용자 경고 시 로그인 시 alert로 경고 생성~~

 ~~**Merge 전에 주석 추가 후 Merge 요청 예정입니다**~~

  개발 예정
  버그 수정 위주의 작업이 들어갈 예정입니다

+ **Additional Info**
개발 시 현재 임시로 사용하고 있는 아이디와 비밀번호는 다음과 같습니다.
**관리자**
ID '0000000001',  PASSWORD 'qwerty123!'
**카페 관리자**
ID '9000000001', PASSWORD 'qwerty123!'
**이용자**
ID '2018311485', PASSWORD 'qwerty123!'
개발에 도움을 위해서 더 필요할 시 dummy User를 추가할 예정입니다.

버그 더 있다면 수정하겠습니다.

#

**Comment by Jehaechan** [comment]
- README 작성
- index.html 개선

두 가지 작업 진행중입니다. 혹시 이 외에 필요한 작업이 있을까요?

**Comment by lieion** [comment]
그 외에는 행사 버튼 사용안하면 그냥 삭제하는 절차 진행하면 될 것 같습니다.
