### ISSUE TITLE
Documentation 관련 문의

### ISSUE THREAD

**Issue by lieion** [lieion/OpenSource_Final_Project#22]
+ **Suggestion**
현재 Implementation 최종단계라 @Jehaechan 문서화 관련해서 분담이 필요할텐데 현재 진행하고 있는 것 말씀해주시면 그 외에 진행하도록 하겠습니다.

**Comment by Jehaechan** [comment]
- README 작성
- index.html 개선

두 가지 작업 진행 중입니다. Server쪽 API 문서 정리 정도가 추가적으로 필요할 것 같은데 혹시 또 문서화 필요한 내용이 있을까요?

**Comment by lieion** [comment]
그럼 index html 개선 완료되면 동영상 촬영 준비 진행하겠습니다

**Comment by Jehaechan** [comment]
그러면 일단 개선된 index.html 까지만 PR하도록 하겠습니다!

**Comment by Jehaechan** [comment]
기존에 Pull Request가 있어서 먼저 merge후 push했어야 하는데, push한 뒤  merge해버려서 이미 main으로 합쳐져버렸네요... 죄송합니다.  
- index.html 개선
- typo: **~blue port~ -> blue pot** - 기존 파일들 파일명 및 변수, 함수명 전부 수정

두가지 사항 커밋하였습니다. 확인 부탁드리겠습니다.

**Comment by lieion** [comment]
git pull 후 merge 이상 없음 확인했습니다.
