### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Jehaechan** [lieion/OpenSource_Final_Project#24]
#### thumbnail.png
 - **thumbnail.png**를 만들어야 합니다.
 - 내용을 어떻게 구성할지 논의가 필요합니다.

**Comment by lieion** [comment]
1. 로고를 크게 디자인해서 만들기
2. 작게 나올 이미지니 글자보다는 성대 카페 + 예약 두 가지에 집중해서 표현해보면 좋을 것 같습니다

**Comment by lieion** [comment]
![내 프로젝트-1](https://user-images.githubusercontent.com/50134433/205028638-38ce00b7-e560-4749-bc18-ecb16bbce198.png)
@Jehaechan 이런 느낌은 어떠신가요?

**Comment by Jehaechan** [comment]
너무 좋은것 같습니다!

**Comment by lieion** [comment]
그럼 크기 맞춰서 commit 요청해놓겠습니다
논외로, ppt작성 후 내일 점심전까진 발표영상 올려놓겠습니다

**Comment by Jehaechan** [comment]
네 알겠습니다. 도움 필요하신 부분 있으면 편하게 말씀해주세요.
(+) 혹시 우수 프로젝트 공모에 참여하실 생각이 있으신가요?
