### ISSUE TITLE
Issue Template 생성

### ISSUE THREAD

**Issue by Jehaechan** [lieion/OpenSource_Final_Project#4]
개발이 필요한 내용들을 issue에 정리해 놓으면 좋을것 같습니다.
#
**개발이 필요한 부분에 대한 이슈를 등록하기 위한 Issue Template 을 다음과 같은 형태로 생성**
* * *   
### Template name
Request_Develop

### About
새로 추가할 기능, 페이지, 파일에 대한 suggest

### Template content
+ **About**
개발이 필요한 Feature에 대한 설명
    예시)
    - 주문 내역 확인 페이지(html 파일)를 추가해야 합니다.
    - XX.js파일에서 XX기능을 추가해야 합니다.
    - 회원 정보를 Database에 추가하는 기능이 필요합니다.

+ **Suggestion**
대략적인 구현 방안 제시
    예시)
    - 각 카페의 메뉴에서 주문할 상품들을 추가하고 "주문하기" 버튼을 눌렀을 때, "주문 내역 확인" 페이지로 넘어가 주문한 리스트들을 확인하고 "주문 완료" 버튼을 누르면 주문이 완료되었다는 팝업 메시지를 띄운다.
    - 회원가입요청에 event handler를 추가하여 사용자가 기입한 내용을 user폴더에 .json파일 형태로 저장한다.
   
+ **Additional Info**
개발할 시 주의해야 할 사항, 다른 file과의 dependency 등 추가적으로 알려줘야 할 내용
    예시)
    - X function과의 dependency에 유의
    - X기능을 추가할 때 Y기능과 충돌이 일어날 수 있음에 유의  
#
혹시 수정할 부분이 있다면 수정해주시고, 괜찮으시다면 이 형태로 issue template을 만들어 앞으로 개발할 내용들을 정리해놓고 pull request시 해당 issue를 연동시켜 놓는게 어떨까요?

**Comment by lieion** [comment]
괜찮은 것 같습니다. 저러면 확실히 merge할 때 편해질 것 같네요

**Comment by Jehaechan** [comment]
이슈 템플릿을 owner만 등록할수 있는것 같습니다. 혹시 위에 적혀진대로 issue template 등록 가능할까요?

**Comment by lieion** [comment]
적용하였습니다. 확인바랍니다

**Comment by Jehaechan** [comment]
확인하였습니다. 혹시 등록된 이슈에 대한 개발을 진행하고 있다면, 해당 이슈에 저를 assign하여 알려드리도록 하겠습니다.

더이상 건의해주실 내용이 없다면 확인 후 이슈 닫으셔도 괜찮을것 같습니다!

**Comment by lieion** [comment]
넵 확인하였습니다.

**Comment by Jehaechan** [comment]
죄송합니다. 수정 사항이 있어 다시 열었습니다. 이슈 템플릿 내용은
#
+ **About**
개발이 필요한 Feature에 대한 설명
    예시)
    - 주문 내역 확인 페이지(html 파일)를 추가해야 합니다.
    - XX.js파일에서 XX기능을 추가해야 합니다.
    - 회원 정보를 Database에 추가하는 기능이 필요합니다.

+ **Suggestion**
대략적인 구현 방안 제시
    예시)
    - 각 카페의 메뉴에서 주문할 상품들을 추가하고 "주문하기" 버튼을 눌렀을 때, "주문 내역 확인" 페이지로 넘어가 주문한 리스트들을 확인하고 "주문 완료" 버튼을 누르면 주문이 완료되었다는 팝업 메시지를 띄운다.
    - 회원가입요청에 event handler를 추가하여 사용자가 기입한 내용을 user폴더에 .json파일 형태로 저장한다.
   
+ **Additional Info**
개발할 시 주의해야 할 사항, 다른 file과의 dependency 등 추가적으로 알려줘야 할 내용
#
이 부분만 넣어주시면 감사하겠습니다!

**Comment by lieion** [comment]
수정했는데 확인해주세요

**Comment by Jehaechan** [comment]
확인했습니다. 감사합니다.
