### ISSUE TITLE
현재 진행 상황 

### ISSUE THREAD

**Issue by lieion** [lieion/OpenSource_Final_Project#5]
<h1>Template name</h1>
김건우 - 진행 상황

<h2>v 0.1.0</h2>
새로 추가할 기능, 페이지, 파일에 대한 suggest

<h2>Template Content</h2>
<h3>About</h3>

**현재 상황 안내**

1. 회원가입 시스템 구현 (express.js) (완)
2. 로그인 시스템 구현 (완)
3. 주문 내역 구현 중 (11/26 예정)
4. myPage 추가 (11/26 예정)
5. navbar issue 관련 수정 #6  (진행 중)
아마도 시간 상 로컬 server.js의 array 형태로 데이터베이스를 대체 (13강 chat 저장 방식 처럼)
회원 가입 요청에는  form 형태를 사용해서 사용자가 기입한 내용을 server로 전달 후 array에 저장. 

**Additional Info**
`npm install body-parser`
`npm install express -save`
필요
로그인 후 받는 토큰으로 인해서 충돌이 일어날 수 있음에 유의

**Comment by Jehaechan** [comment]
확인했습니다! 저도 빠른 시일 내에 진행 사항 업로드하도록 하겠습니다.
