### ISSUE TITLE
Navbar 동작 방식 수정

### ISSUE THREAD

**Issue by Jehaechan** [lieion/OpenSource_Final_Project#6]
+ **About**
Navbar의 button들이 navbar-toggle클래스로 등록되어 카페 버튼을 누르면 navbar 전체가 내려오며 menu들이 보이게 되는데, navbar는 그대로 있고 menu들만 새로운 box에 나오도록 하면 좋을 것 같습니다.

+ **Suggestion**
bootstrap의 dropdown기능을 사용하면 될것 같습니다.
   
+ **Additional Info**
각 메뉴들의 위치도 수정되면 좋을것 같습니다.

**Comment by lieion** [comment]
다음 수정 사항에 넣어놓겠습니다

**Comment by Jehaechan** [comment]
제가 수정중입니다. (저에게 Issue assign해 두었습니다)
