### ISSUE TITLE
진행 상황

### ISSUE THREAD

**Issue by Jehaechan** [lieion/OpenSource_Final_Project#8]
## 현재 상황 안내

1. #6 ~~진행 완료~~
1. ~~각 카페별 지도 페이지 추가(진행 중)~~
1. ~~각 카페별 메뉴 페이지 추가(진행 중)~~
1. Main page 수정(진행 중)
1. Login page 수정(진행 중)

## Additional
몇가지 질문 사항이 있습니다. @lieion 
1. SignUpUser.html파일과 sign-up.html파일의 차이점이 무엇인가요?
1. 위 페이지 외에 추가적으로 필요한 페이지가 있으면 쓰레드로 추가하거나 issue 생성해주시면 감사하겠습니다.

**Comment by lieion** [comment]
페이지 복사하다가 같은 페이지가 된 모양입니다. SignUpUser.html 파일은 삭제하거나 비밀번호 수정페이지로 바꾸겠습니다.
